version: "3.4"
services:
  backend:
    container_name: backend
    hostname: backend
    image: ksproska/tictactoe-aws-backend
    network_mode: "host"
    env_file:
    - domain.env
    - aws-credentials.env
    - db.env

  frontend:
    container_name: frontend
    hostname: frontend
    image: ksproska/tictactoe-aws-frontend
    network_mode: "host"
    env_file: domain.env
