version: "3.4"
services:
  backend:
    container_name: backend
    hostname: backend
    build:
      context: backend
      dockerfile: Dockerfile
      target: "backend"
    networks:
      - priv-network
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    hostname: frontend
    build: frontend
    networks:
      - priv-network
    ports:
      - "4200:4200"

networks:
  priv-network:
    driver: bridge
