version: "3.4"
services:
  db:
    container_name: db
    hostname: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=tictactoe
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=password
    networks:
      - priv-network
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 30
      interval: 2s

  backend:
    container_name: backend
    hostname: backend
    build:
      context: backend
      dockerfile: Dockerfile
      target: "backend"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tictactoe?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
    networks:
      - priv-network
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080/healthcheck" ]
      interval: 2s
      retries: 30

  frontend:
    container_name: frontend
    hostname: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      target: "frontend"
    networks:
      - priv-network
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy

networks:
  priv-network:
    driver: bridge
