version: "3.4"
services:
  backend:
    container_name: backend
    hostname: backend
    image: ksproska/tictactoe-aws-backend
    network_mode: "host"
    environment:
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: tictactoe2023!
      SPRING_DATASOURCE_URL: jdbc:mysql://database-1.cwcuuvfyrh3z.us-east-1.rds.amazonaws.com:3306/tictactoe

  frontend:
    container_name: frontend
    hostname: frontend
    image: ksproska/tictactoe-aws-frontend
    network_mode: "host"
